# frontend/Dockerfile.prod
FROM node:22.4.0 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build

FROM nginx:latest
COPY --from=builder /app/dist /usr/share/nginx/html

COPY /nginx/default.conf.template /etc/nginx/conf.d/default.conf.template
COPY /nginx/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
