services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./database/init-data.dump:/docker-entrypoint-initdb.d/init.dump
    networks:
      - backend-network

  express-app:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      args:
        BACKEND_PORT: ${BACKEND_PORT}
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - SITE_URL=${SITE_URL}
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - express-app
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - frontend-network
      - backend-network
volumes:
  pgdata-prod:

networks:
  frontend-network:
  backend-network:
