FROM node:22.4.0

WORKDIR /usr/src/app

ARG BACKEND_PORT

ENV BACKEND_PORT=$BACKEND_PORT

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE $BACKEND_PORT

CMD ["node", "dist/index.js"]
